spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  jpa:
    show-sql: true
  data:
    rest:
      base-path: api
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

taco:
  orders:
    pageSize: 10
server:
  port: 9090
logging:
  level:
    tacos: DEBUG
