spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  jpa:
    show-sql: true
  data:
    rest:
      base-path: /data-api
taco:
  orders:
    pageSize: 10
logging:
  level:
    tacos: DEBUG
