drop table if exists ingredient cascade;
drop table if exists taco cascade;
drop table if exists taco_ingredients cascade;
drop table if exists taco_user cascade;
drop table if exists taco_order cascade;
drop table if exists taco_order_tacos cascade;
drop
sequence if exists taco_order_seq;
drop
sequence if exists taco_seq;
create
sequence taco_order_seq start
with 1 increment by 50;
create
sequence taco_seq start
with 1 increment by 50;
create table ingredient
(
    id   varchar(4)  not null,
    name varchar(25) not null,
    type varchar(10) not null,
    primary key (id)
);
create table taco
(
    id         bigint       not null,
    created_at timestamp(6),
    name       varchar(255) not null,
    taco_order bigint,
    primary key (id)
);
create table taco_ingredients
(
    taco_id        bigint     not null,
    ingredients_id varchar(4) not null
);
create table taco_user
(
    id           bigint generated by default as identity,
    city         varchar(255),
    fullname     varchar(255),
    password     varchar(255),
    phone_number varchar(255),
    state        varchar(255),
    street       varchar(255),
    username     varchar(255),
    zip          varchar(255),
    primary key (id)
);
create table taco_order
(
    id              bigint       not null,
    cccvv           varchar(3)   not null,
    cc_expiration   varchar(5)   not null,
    cc_number       varchar(16)  not null,
    delivery_city   varchar(50)  not null,
    delivery_name   varchar(50)  not null,
    delivery_state  varchar(2)   not null,
    delivery_street varchar(50)  not null,
    delivery_zip    varchar(10)  not null,
    placed_at       timestamp(6) not null,
    primary key (id)
);
create table taco_order_tacos
(
    taco_order_id bigint not null,
    tacos_id      bigint not null
);
alter table if exists taco_order_tacos add constraint UK_r4rma0h2pka5irll8qnlnwlwh unique (tacos_id);
alter table if exists taco add constraint FK4c2bi04jd4qtiqs1bw7cjlbsi foreign key (taco_order) references taco_order;
alter table if exists taco_ingredients add constraint FK7y679y77n5e75s3ss1v7ff14j foreign key (ingredients_id) references ingredient;
alter table if exists taco_ingredients add constraint FK27rycuh3mjaepnba0j6m8xl4q foreign key (taco_id) references taco;
alter table if exists taco_order_tacos add constraint FKfwvqtnjfview9e5f7bfqtd1ns foreign key (tacos_id) references taco;
alter table if exists taco_order_tacos add constraint FKs8yteduju5tndbivxbmdrbsyy foreign key (taco_order_id) references taco_order;
   